### ISSUE TITLE
Add support for connecting through proxies

### ISSUE THREAD

**Issue by Shamunr** [hagen1778/fasthttploader#1]
Being able to specify a proxy to connect as would be nice to have so benchmarking the proxy can be done.  An added bonus to that would be to specify a list of proxies (or a file containing a new proxy on every line) so mass testing can be done.

**Comment by hagen1778** [comment]
I fully support the view of @wg in this question (https://github.com/wg/wrk/issues/6)
Testing service through proxy might lead to wrong results
